"""KML (Keyhole Markup Language) Exporter for Hydrographic & Marine Debris Targets.

Generates standard OGC KML 2.2 documents for 3D visualization in Google Earth,
ECDIS nautical consoles, and OpenCPN navigation displays.
"""

from __future__ import annotations

import html
from typing import Any, Dict, List


RISK_COLORS = {
    "critical": "ff0000ff",  # Red in KML AABBGGRR
    "high": "ff0055ff",      # Orange-red
    "medium": "ff00aaff",    # Amber
    "low": "ff00ff00",       # Green
}


class KMLService:
    """Exports acoustic detection targets to formatted OGC KML."""

    def generate_kml(self, detections: List[Dict[str, Any]], survey_title: str = "Sonar Sentry Acoustic Survey") -> str:
        kml_header = f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>{html.escape(survey_title)}</name>
    <description>Hydrographic side-scan sonar targets with SADH physics verification and hazard ranking.</description>
    
    <!-- Custom Style Definitions for Threat Levels -->
    <Style id="criticalHazard">
      <IconStyle>
        <color>{RISK_COLORS['critical']}</color>
        <scale>1.3</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/shapes/caution.png</href></Icon>
      </IconStyle>
      <LabelStyle><scale>0.9</scale></LabelStyle>
    </Style>
    <Style id="highHazard">
      <IconStyle>
        <color>{RISK_COLORS['high']}</color>
        <scale>1.2</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/shapes/warning.png</href></Icon>
      </IconStyle>
      <LabelStyle><scale>0.8</scale></LabelStyle>
    </Style>
    <Style id="mediumHazard">
      <IconStyle>
        <color>{RISK_COLORS['medium']}</color>
        <scale>1.0</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href></Icon>
      </IconStyle>
      <LabelStyle><scale>0.8</scale></LabelStyle>
    </Style>
    <Style id="lowHazard">
      <IconStyle>
        <color>{RISK_COLORS['low']}</color>
        <scale>0.9</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/shapes/info.png</href></Icon>
      </IconStyle>
    </Style>
"""

        placemarks = []
        for det in detections:
            lat = det.get("latitude")
            lon = det.get("longitude")
            if lat is None or lon is None:
                continue

            target_id = str(det.get("id", "TARGET"))[:12]
            label = str(det.get("class_label", "Debris")).title()
            conf = float(det.get("confidence", 0.0)) * 100.0
            risk = str(det.get("risk_level", "medium")).lower()
            height_m = det.get("sadh_height_m", 0.0)
            depth_m = det.get("depth_m", 0.0)

            style_id = "mediumHazard"
            if "crit" in risk:
                style_id = "criticalHazard"
            elif "high" in risk:
                style_id = "highHazard"
            elif "low" in risk:
                style_id = "lowHazard"

            description_html = f"""<![CDATA[
              <h3>{html.escape(label)} (#{html.escape(target_id)})</h3>
              <table border="1" cellpadding="4" cellspacing="0" style="font-family: sans-serif; font-size: 12px;">
                <tr><td><b>Neural Confidence:</b></td><td>{conf:.1f}%</td></tr>
                <tr><td><b>Hazard Level:</b></td><td>{risk.upper()}</td></tr>
                <tr><td><b>Target Height (h):</b></td><td>{float(height_m):.2f} m</td></tr>
                <tr><td><b>Seafloor Depth:</b></td><td>{float(depth_m):.1f} m</td></tr>
                <tr><td><b>WGS-84 Coordinates:</b></td><td>{float(lat):.6f}°N, {float(lon):.6f}°E</td></tr>
              </table>
              <p><i>Generated by SonarShield AI Defense &amp; Salvage Platform</i></p>
            ]]>"""

            placemarks.append(f"""    <Placemark>
      <name>{html.escape(label)} ({target_id})</name>
      <styleUrl>#{style_id}</styleUrl>
      <description>{description_html}</description>
      <Point>
        <coordinates>{float(lon):.6f},{float(lat):.6f},{-abs(float(depth_m))}</coordinates>
      </Point>
    </Placemark>""")

        kml_footer = """  </Document>
</kml>"""

        return kml_header + "\n".join(placemarks) + "\n" + kml_footer


kml_service = KMLService()
